import { promises as fs } from "fs";
import { rimraf } from "rimraf";
import path from "path";

import { project } from "../content/projects/item/index";

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {`;

  for (const item of project.items) {
    index += `
  "${item.name}": {
      "name": "${item.name}",
      "description": "${item.description}",
      "challenge": ${JSON.stringify(item.challenge)},
      "learning": ${JSON.stringify(item.learning)},
      "techstack": ${JSON.stringify(item.techstack)},
      "preview": "${item.preview}",
      "github": "${item.github}",
      "timeline": "${item.timeline}",
      "teamsize": "${item.teamsize}",
      "role": "${item.role}",
      "status": "${item.status}"
    }
  `;
  }
  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(project.items).length} items found`);

  // Write style index.
  rimraf.sync(path.join(process.cwd(), "content/projects/__index__.tsx"));
  await fs.writeFile(
    path.join(process.cwd(), "content/projects/__index__.tsx"),
    index
  );
}

try {
  console.log("🗂️ Building content/projects/__index__.tsx...");
  await buildRegistryIndex();
  console.log("🥳 Completed content/projects/__index__.tsx...");

  console.log("🥳 Completed all process check the changes...");
} catch (error) {
  console.error(error);
  process.exit(1);
}
